export const SET_AUTHED_USER = 'SET_AUTHED_USER';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const CREATE_NEW_QUESTION = 'CREATE_NEW_QUESTION';
export const CREATE_NEW_ANSWER = 'CREATE_NEW_ANSWER';
